apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stone-teste-api-ingress
  namespace: stone-teste-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/add-base-url: "true"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: stone-teste-api-service
                port:
                  number: 80
