apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: stone-teste-api
  name: namespace-manager
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "create"]
