apiVersion: v1
kind: Service
metadata:
  name: stone-teste-api-service
  namespace: stone-teste-api
spec:
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: stone-teste-api
  type: NodePort