name: Deploy Staging

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        id: build-image
        run: |
          IMAGE_TAG=staging
          docker buildx build --platform linux/amd64 -t ${{ secrets.AWS_ECR_REGISTRY_STGN }}/${{ secrets.AWS_ECR_REPOSITORY_STGN }}:$IMAGE_TAG --push .

      - name: Create namespace
        env:
          EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
        run: |
          aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region ${{ secrets.AWS_REGION }}
          kubectl apply -f envs/staging/namespace-stgn.yml

      - name: Update Kubernetes deployment
        env:
          EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
          IMAGE_TAG: staging
        run: |
          aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region ${{ secrets.AWS_REGION }}
          kubectl apply -f envs/staging/deployment-stgn.yml
          kubectl set image deployment/stone-teste-api-stgn stone-teste-api-stgn=${{ secrets.AWS_ECR_REGISTRY }}/${{ secrets.AWS_ECR_REPOSITORY }}:$IMAGE_TAG -n stone-teste-api-stgn
          kubectl apply -f envs/staging/service-stgn.yml
          kubectl apply -f envs/staging/ingress-stgn.yml
          kubectl apply -f envs/staging/clusterrole-stgn.yml
          kubectl apply -f envs/staging/clusterrolebinding-stgn.yml
