name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Confirm to destroy resources'
        required: true
        type: boolean
      environment:
        description: 'Environment to destroy (prod or stgn)'
        required: true
        type: choice
        options:
          - prod
          - stgn

jobs:
  terraform:
    name: Terraform Destroy
    runs-on: ubuntu-latest

    if: ${{ github.event.inputs.destroy == 'true' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set environment variable
        run: echo "TF_VAR_ENV=${{ github.event.inputs.environment }}" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init -backend-config="path=environments/${{ env.TF_VAR_ENV }}/terraform.tfstate"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan Destroy
        run: terraform plan -destroy -var-file="environments/${{ env.TF_VAR_ENV }}/terraform.tfvars"

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var-file="environments/${{ env.TF_VAR_ENV }}/terraform.tfvars"
